name: Build
on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: actions/checkout@v2
      - name: Maven build and deploy
        run: |
          mvn test
          mvn clean deploy
  
  Analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
    
      - uses: actions/checkout@v2    
      - name: analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B test org.sonarsource.scanner.maven:sonar-maven-plugin:sonar  -Dsonar.projectKey=Kalaiselvan92_github-actions -Dsonar.organization= kalaiselvan92
